Repository Dev-FE-3/toy-project3-team3, pull requests merged in 2025-04, with the labels that each got.

#1 Docs : Supabase 및 초기 설정
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/index.css
  src/lib/supabase.ts
  src/main.tsx
  src/pages/home/Home.tsx
  src/shared/Layout.tsx
Labels: 📜 Docs

#4 Feat : component scrollbar & Global, Reset style
  src/App.tsx
  src/assets/fonts/NotoSansKR-Bold.ttf
  src/assets/fonts/NotoSansKR-Bold.woff
  src/assets/fonts/NotoSansKR-Bold.woff2
  src/assets/fonts/NotoSansKR-Medium.ttf
  src/assets/fonts/NotoSansKR-Medium.woff
  src/assets/fonts/NotoSansKR-Medium.woff2
  src/assets/fonts/NotoSansKR-Regular.ttf
  src/assets/fonts/NotoSansKR-Regular.woff
  src/assets/fonts/NotoSansKR-Regular.woff2
  src/shared/styles/GlobalStyle.tsx
  src/shared/styles/fonts.ts
Labels: ✨ Feature

#9 Feat: button 컴포넌트 제작
  src/App.tsx
  src/pages/guide/Guide.tsx
  src/shared/component/Button.tsx
Labels: ✨ Feature

#6 Feat: modal 컴포넌트 제작
  src/App.tsx
  src/assets/images/cancel.svg
  src/pages/guide/Guide.tsx
  src/pages/guide/ModalGuide.tsx
  src/shared/component/Modal.tsx
Labels: ✨ Feature

#7 Feat : component nav바
  package-lock.json
  package.json
  public/fonts/NotoSansKR-Bold.ttf
  public/fonts/NotoSansKR-Bold.woff
  public/fonts/NotoSansKR-Bold.woff2
  public/fonts/NotoSansKR-Medium.ttf
  public/fonts/NotoSansKR-Medium.woff
  public/fonts/NotoSansKR-Medium.woff2
  public/fonts/NotoSansKR-Regular.ttf
  public/fonts/NotoSansKR-Regular.woff
  public/fonts/NotoSansKR-Regular.woff2
  src/App.tsx
  src/assets/images/Home.svg
  src/assets/images/Inbox.svg
  src/assets/images/Plus.svg
  src/assets/images/Search.svg
  src/pages/guide/Guide.tsx
  src/pages/guide/ModalGuide.tsx
  src/pages/search/Search.tsx
  src/shared/Layout.tsx
  src/shared/Nav.tsx
  src/shared/styles/fonts.ts
Labels: ✨ Feature

#11 Feat : input 컴포넌트 제작
  package-lock.json
  src/pages/guide/Guide.tsx
  src/shared/component/input.tsx
Labels: ✨ Feature

#10 Feat : component header
  src/App.tsx
  src/assets/images/IdolLink.svg
  src/assets/images/defaultProfile.svg
  src/pages/auth/Login.tsx
  src/pages/profile/Profile.tsx
  src/shared/Header.tsx
  src/shared/Layout.tsx
Labels: ✨ Feature

#13 Feat : 로그인, 로그아웃, protectedRoute 설정
  src/App.tsx
  src/pages/auth/Login.tsx
  src/pages/storage/Storage.tsx
  src/shared/Header.tsx
  src/shared/Layout.tsx
  src/shared/component/ProtectedRoute.tsx
Labels: ✨ Feature

#16 Feat : login 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/Signup.tsx
  src/shared/component/input.tsx
Labels: ✨ Feature, 🎨 Html & css

#20 Feat : Title 컴포넌트 제작
  src/assets/images/GoBack.svg
  src/assets/images/Like.svg
  src/pages/guide/Guide.tsx
  src/shared/component/Button.tsx
  src/shared/component/Title.tsx
  src/shared/styles/GlobalStyle.tsx
Labels: ✨ Feature

#18 Feat: 드롭다운 공통 컴포넌트 구현
  src/pages/guide/Guide.tsx
  src/shared/component/Dropbox.tsx
Labels: ✨ Feature

#19 Feat : profile 페이지 퍼블리싱 & 이미지 업로드
  package-lock.json
  package.json
  src/assets/images/defaultProfile.svg
  src/pages/profile/Profile.tsx
  src/pages/profile/hooks/useDeleteProfileImage.ts
  src/pages/profile/hooks/useUploadProfileImage.ts
  src/pages/storage/Storage.tsx
  src/shared/Header.tsx
  src/shared/component/Dropbox.tsx
  src/shared/component/input.tsx
  src/shared/hooks/useUserProfile.ts
  src/shared/styles/GlobalStyle.tsx
Labels: ✨ Feature, 🎨 Html & css

#25 Feat: Axios를 이용해 Supabase와 연동
  package-lock.json
  package.json
  src/api/axiosInstance.ts
  src/api/comment.ts
  src/api/follow.ts
  src/api/like.ts
  src/api/playlist.ts
  src/api/users.ts
  src/api/video.ts
Labels: 📜 Docs, ✨ Feature

#22 Feat : 회원가입 페이지 퍼블리싱 및 로직 구현
  package-lock.json
  package.json
  src/main.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/Signup.tsx
  src/pages/auth/component/FormInput.tsx
  src/pages/guide/Guide.tsx
  src/shared/component/ToastProvider.tsx
Labels: ✨ Feature, 🎨 Html & css

#23 Feat : home 페이지
  src/assets/images/backGround.png
  src/assets/images/comment.svg
  src/pages/home/Home.tsx
  src/shared/Layout.tsx
Labels: ✨ Feature, 🎨 Html & css

#28 Feat : profile 페이지 제작
  package-lock.json
  package.json
  src/App.tsx
  src/api/services/getCurrentUser.ts
  src/api/users.ts
  src/assets/images/Plus.svg
  src/main.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/hooks/useDeleteProfileImage.ts
  src/pages/profile/hooks/useUpdateUserInfo.ts
  src/pages/profile/hooks/useUploadDeleteProfileImage.ts
  src/pages/profile/hooks/useUploadProfileImage.ts
  src/pages/storage/Storage.tsx
  src/shared/Header.tsx
  src/shared/Nav.tsx
  src/shared/component/Modal.tsx
  src/shared/component/input.tsx
  src/shared/hooks/useProfileImage.ts
  src/shared/hooks/useUser.ts
  src/shared/hooks/useUserProfile.ts
  src/stores/lockStore.ts
  src/stores/userStore.ts
Labels: ✨ Feature

#26 Feat : storage 페이지 퍼블리싱
  src/App.tsx
  src/pages/storage/storage.tsx
Labels: ✨ Feature, 🎨 Html & css

#27 Style: 플레이리스트 생성 페이지 퍼블리싱
  src/App.tsx
  src/assets/images/add.svg
  src/pages/guide/Guide.tsx
  src/pages/playlist/Create.tsx
  src/pages/playlist/component/VideoItem.tsx
  src/pages/storage/Storage.tsx
  src/pages/storage/storage.tsx
  src/shared/component/Modal.tsx
  src/shared/styles/GlobalStyle.tsx
Labels: 🎨 Html & css

#29 Feat : api interface 수정
  src/api/comment.ts
  src/api/follow.ts
  src/api/like.ts
  src/api/users.ts
  src/pages/storage/Storage.tsx
Labels: ✨ Feature

#32 Style : Play 페이지, Icon 공통 컴포넌트 제작
  src/App.tsx
  src/api/users.ts
  src/assets/images/GoBack.svg
  src/assets/images/List.svg
  src/assets/images/Submit.svg
  src/pages/play/Play.tsx
  src/pages/storage/Storage.tsx
  src/shared/component/Icon.tsx
  src/shared/component/Title.tsx
  src/shared/styles/GlobalStyle.tsx
Labels: 🎨 Html & css

#30 Feat/home 기능 구현
  src/App.tsx
  src/api/like.ts
  src/api/playlist.ts
  src/api/playlistCardData.ts
  src/api/services/likeActive.ts
  src/assets/images/Like.svg
  src/assets/images/originLike.svg
  src/pages/home/Home.tsx
  src/pages/homeAndSearch/Home.tsx
  src/pages/homeAndSearch/Search.tsx
  src/pages/homeAndSearch/component/PlaylistCard.tsx
  src/pages/search/Search.tsx
Labels: ✨ Feature

#33 Feat : storage & follow info 기능 제작
  package-lock.json
  src/App.tsx
  src/api/follow.ts
  src/api/like.ts
  src/api/playlist.ts
  src/api/playlistCardData.ts
  src/api/services/getCurrentUser.ts
  src/api/services/getMyPlaylists.ts
  src/api/services/useFollowCount.ts
  src/api/services/useFollowList.ts
  src/api/services/useFollowMutation.ts
  src/api/services/useLikedPlaylists.ts
  src/api/services/useMyPlaylists.ts
  src/api/services/useOtherUser.ts
  src/api/users.ts
  src/assets/images/Like.svg
  src/assets/images/reset.svg
  src/pages/auth/Signup.tsx
  src/pages/followInfo/FollowInfo.tsx
  src/pages/followInfo/hooks/useFollowStatus.ts
  src/pages/followInfo/utils/debounce.ts
  src/pages/homeAndSearch/Home.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/hooks/useUpdateUserInfo.ts
  src/pages/storage/NavigateToMyStorage.tsx
  src/pages/storage/Storage.tsx
  src/shared/Header.tsx
  src/shared/component/Dropbox.tsx
  src/shared/component/Icon.tsx
  src/shared/component/ProtectedRoute.tsx
  src/shared/component/input.tsx
Labels: ✨ Feature

#39 Feat : storage 수정
  src/api/playlistCardData.ts
  src/api/services/useLikedPlaylists.ts
  src/api/services/useMyPlaylists.ts
  src/api/services/useOtherUser.ts
  src/pages/profile/Profile.tsx
  src/pages/storage/Storage.tsx
Labels: ✨ Feature

#36 Feat : home & search 제작
  src/App.tsx
  src/api/playlistCardData.ts
  src/api/services/getMyPlaylists.ts
  src/api/services/likeActive.ts
  src/api/services/useLikedPlaylists.ts
  src/assets/images/Like.svg
  src/pages/followInfo/FollowInfo.tsx
  src/pages/followInfo/utils/debounce.ts
  src/pages/homeAndSearch/Home.tsx
  src/pages/homeAndSearch/Search.tsx
  src/pages/homeAndSearch/component/PlaylistCard.tsx
  src/pages/homeAndSearch/hooks/useHomeFeedPlaylists.ts
  src/pages/homeAndSearch/hooks/useLikedPlaylistIds.ts
  src/pages/storage/hooks/NavigateToMyStorage.tsx
  src/shared/hooks/useDebounce.ts
Labels: ✨ Feature

#41 Chore : cypress 설정
  cypress.config.js
  cypress/e2e/profile/profile.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
Labels: ⚙ Setting

#38 Feat/detail 페이지
  src/App.tsx
  src/api/comment.ts
  src/api/like.ts
  src/api/playlistWithvideos.ts
  src/api/users.ts
  src/api/video.ts
  src/assets/images/Like.svg
  src/pages/homeAndSearch/Home.tsx
  src/pages/homeAndSearch/Search.tsx
  src/pages/homeAndSearch/component/PlaylistCard.tsx
  src/pages/playlist/detail/Detail.tsx
  src/pages/playlist/detail/hooks/useLikeStatus.ts
Labels: ✨ Feature, 🎨 Html & css

#43 Feat : layout과 Heart 이벤트 수정
  src/pages/homeAndSearch/Home.tsx
  src/pages/homeAndSearch/Search.tsx
  src/pages/profile/Profile.tsx
  src/pages/storage/Storage.tsx
  src/shared/Layout.tsx
Labels: 🐞 Bugfix, 🎨 Html & css

#44 Feat/play 페이지
  src/App.tsx
  src/api/comment.ts
  src/api/playlistFullView.ts
  src/pages/play/Play.tsx
  src/pages/play/hooks/usePlayPage.ts
  src/pages/playlist/detail/Detail.tsx
  src/shared/hooks/usePlaylistMeta.ts
Labels: ✨ Feature, 🎨 Html & css

#45 Fix : detail 페이지 토글 및 play 페이지 수정
  src/api/comment.ts
  src/pages/play/Play.tsx
  src/pages/playlist/detail/Detail.tsx
  src/shared/hooks/usePlaylistMeta.ts
Labels: 🐞 Bugfix, ✨ Feature

#50 Feat : play 페이지 프로필 이미지 navigate 연결
  src/api/comment.ts
  src/api/playlistCardData.ts
  src/pages/homeAndSearch/Search.tsx
  src/pages/play/Play.tsx
  src/pages/playlist/detail/Detail.tsx
Labels: ✨ Feature

#47 Feat : auth & 플레이리스트 생성 페이지 e2e 테스트
  .gitignore
  cypress.config.js
  cypress/e2e/auth/auth.cy.ts
  cypress/e2e/playlsit/create.cy.ts
  cypress/fixtures/testimage.jpg
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/Signup.tsx
  src/pages/guide/Guide.tsx
  src/pages/playlist/Create.tsx
  src/pages/playlist/component/VideoItem.tsx
  src/pages/storage/Storage.tsx
  src/shared/Header.tsx
  src/shared/Nav.tsx
  src/shared/component/Modal.tsx
  tsconfig.app.json
Labels: ✨ Feature, 🎨 Html & css

#49 Docs: readme 작성
  README.md
Labels: 📜 Docs

#53 Refactor: api 폴더 구조 변경
  src/api/getCurrentUser.ts
  src/api/getMyPlaylists.ts
  src/api/likeActive.ts
  src/api/uploadPlaylist.ts
  src/api/useFollowCount.ts
  src/api/useFollowList.ts
  src/api/useFollowMutation.ts
  src/api/useLikedPlaylists.ts
  src/api/useMyPlaylists.ts
  src/api/useOtherUser.ts
  src/db/axiosInstance.ts
  src/db/comment.ts
  src/db/follow.ts
  src/db/getPlaylistDetail.ts
  src/db/like.ts
  src/db/playlist.ts
  src/db/playlistCardData.ts
  src/db/playlistFullView.ts
  src/db/playlistWithvideos.ts
  src/db/users.ts
  src/db/video.ts
  src/db/youtube.ts
  src/pages/followInfo/FollowInfo.tsx
  src/pages/followInfo/hooks/useFollowStatus.ts
  src/pages/homeAndSearch/Search.tsx
  src/pages/homeAndSearch/hooks/useHomeFeedPlaylists.ts
  src/pages/homeAndSearch/hooks/useLikedPlaylistIds.ts
  src/pages/play/Play.tsx
  src/pages/playlist/Modify.tsx
  src/pages/playlist/detail/Detail.tsx
  src/pages/playlist/detail/hooks/useLikeStatus.ts
  src/pages/playlist/hooks/useUpdatePlaylist.ts
  src/pages/playlist/hooks/useUploadPlaylist.ts
  src/pages/playlist/hooks/useYoutubeInfo.ts
  src/pages/profile/Profile.tsx
  src/pages/profile/hooks/useUpdateUserInfo.ts
  src/pages/profile/hooks/useUploadDeleteProfileImage.ts
  src/pages/storage/Storage.tsx
  src/shared/hooks/useUser.ts
  src/stores/userStore.ts
Labels: 🔨 Refactor

#55 Refactor : Storage, Profile, FollowInfo 리팩터링
  src/api/getMyPlaylists.ts
  src/api/likeActive.ts
  src/api/useFollowCount.ts
  src/api/useFollowList.ts
  src/api/useFollowMutation.ts
  src/api/useFollowStatus.ts
  src/api/useLikedPlaylists.ts
  src/api/useMyPlaylists.ts
  src/api/useOtherUser.ts
  src/api/useUpdateUserInfo.ts
  src/api/useUploadDeleteProfileImage.ts
  src/constants/queryKey.ts
  src/db/comment.ts
  src/db/follow.ts
  src/db/like.ts
  src/db/playlist.ts
  src/db/playlistCardData.ts
  src/db/users.ts
  src/db/video.ts
  src/pages/followInfo/FollowInfo.tsx
  src/pages/homeAndSearch/hooks/useHomeFeedPlaylists.ts
  src/pages/play/Play.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/component/ProfileForm.tsx
  src/pages/profile/component/ProfileImageSection.tsx
  src/pages/profile/component/renderHashTags.tsx
  src/pages/profile/hooks/useUploadDeleteProfileImage.ts
  src/pages/storage/Storage.tsx
  src/pages/storage/component/StoragePlaylistCard.tsx
  src/pages/storage/component/StorageProfileCard.tsx
  src/shared/component/Tab.tsx
  src/shared/hooks/useDebounce.ts
  src/shared/hooks/useProfileImage.ts
  src/shared/hooks/useUser.ts
Labels: 🔨 Refactor

#57 Refactor : auth, Modify, Create, e2e test 리팩토링
  cypress/e2e/auth/auth.cy.ts
  cypress/e2e/playlsit/create.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  index.html
  src/api/getMyPlaylists.ts
  src/db/getPlaylistDetail.ts
  src/db/playlistWithvideos.ts
  src/db/video.ts
  src/main.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/Signup.tsx
  src/pages/auth/component/FormInput.tsx
  src/pages/playlist/Create.tsx
  src/pages/playlist/Modify.tsx
  src/pages/playlist/hooks/useThumbnailUpload.ts
  src/pages/playlist/hooks/useUpdatePlaylist.ts
  src/pages/playlist/hooks/useUploadPlaylist.ts
  src/pages/playlist/utils/convertToFile.ts
  src/pages/playlist/utils/diffVideoList.ts
  src/types/video.ts
Labels: 🔨 Refactor

#59 Refactor : 플레이리스트 관련 api 코드 및 유튜브 영상 이미지 업로드 방식 개선
  src/db/playlist.ts
  src/db/video.ts
  src/pages/playlist/Create.tsx
  src/pages/playlist/Modify.tsx
  src/pages/playlist/hooks/useUpdatePlaylist.ts
  src/pages/playlist/hooks/useUploadPlaylist.ts
  src/shared/component/Modal.tsx
Labels: 🔨 Refactor

#60 Refactor : API isError, isLoading 반영한 페이지 수정 및 ErrorFallback component 제작
  src/api/getMyPlaylists.ts
  src/pages/followInfo/FollowInfo.tsx
  src/pages/profile/Profile.tsx
  src/pages/storage/Storage.tsx
  src/shared/component/ErrorFallback.tsx
Labels: 🔨 Refactor

#61 Refactor : ErrorFallback 적용 & api, db 위치 변경
  src/api/getCurrentUser.ts
  src/api/useFollowMutation.ts
  src/pages/auth/Login.tsx
  src/pages/auth/Signup.tsx
  src/pages/followInfo/FollowInfo.tsx
  src/pages/homeAndSearch/Search.tsx
  src/pages/homeAndSearch/hooks/useHomeFeedPlaylists.ts
  src/pages/homeAndSearch/hooks/useLikedPlaylistIds.ts
  src/pages/play/Play.tsx
  src/pages/playlist/Modify.tsx
  src/pages/playlist/detail/Detail.tsx
  src/pages/playlist/detail/hooks/useLikeStatus.ts
  src/pages/playlist/hooks/useThumbnailUpload.ts
  src/pages/playlist/hooks/useUpdatePlaylist.ts
  src/pages/playlist/hooks/useUploadPlaylist.ts
  src/pages/playlist/hooks/useYoutubeInfo.ts
  src/pages/playlist/utils/diffVideoList.ts
  src/pages/profile/Profile.tsx
  src/pages/profile/hooks/useOtherUser.ts
  src/pages/profile/hooks/useUpdateUserInfo.ts
  src/pages/profile/hooks/useUploadDeleteProfileImage.ts
  src/pages/storage/Storage.tsx
  src/pages/storage/hooks/useFollowCount.ts
  src/pages/storage/hooks/useFollowStatus.ts
  src/pages/storage/hooks/useLikedPlaylists.ts
  src/pages/storage/hooks/useMyPlaylists.ts
  src/shared/Header.tsx
  src/shared/api/axiosInstance.ts
  src/shared/api/comment.ts
  src/shared/api/follow.ts
  src/shared/api/like.ts
  src/shared/api/likeActive.ts
  src/shared/api/playlist.ts
  src/shared/api/playlistCardData.ts
  src/shared/api/playlistFullView.ts
  src/shared/api/playlistWithvideos.ts
  src/shared/api/uploadPlaylist.ts
  src/shared/api/users.ts
  src/shared/api/video.ts
  src/shared/api/youtube.ts
  src/shared/constants/queryKey.ts
  src/shared/hooks/useFollowList.ts
  src/shared/hooks/useProfileImage.ts
  src/shared/hooks/useUser.ts
  src/shared/lib/supabase.ts
  src/shared/types/video.ts
  src/stores/userStore.ts
Labels: 🔨 Refactor

#62 Refactor : modal alert 적용 & useUpdatePlaylist const 기반 리팩터링
  src/pages/playlist/hooks/useUpdatePlaylist.ts
  src/shared/Header.tsx
Labels: 🔨 Refactor

#58 Refactor: DropBox, PlaylistCard, useLikeStatus(detail페이지 훅), Play 페이지 컴포넌트 분리 리팩토링
  src/App.tsx
  src/pages/detail/Detail.tsx
  src/pages/detail/hooks/useLikeStatus.ts
  src/pages/homeAndSearch/Home.tsx
  src/pages/homeAndSearch/Search.tsx
  src/pages/homeAndSearch/component/PlaylistCard.tsx
  src/pages/play/Play.tsx
  src/pages/play/component/CommentSection.tsx
  src/pages/play/component/VideoMetaSection.tsx
  src/pages/play/hooks/usePlayPage.ts
  src/pages/playlist/detail/hooks/useLikeStatus.ts
  src/pages/playlist/hooks/useYoutubeInfo.ts
  src/pages/playlist/utils/ExtractVideoId.ts
  src/pages/profile/Profile.tsx
  src/pages/storage/Storage.tsx
  src/pages/storage/component/StoragePlaylistCard.tsx
  src/shared/api/comment.ts
  src/shared/api/follow.ts
  src/shared/api/like.ts
  src/shared/api/likeActive.ts
  src/shared/api/playlist.ts
  src/shared/api/playlistCardData.ts
  src/shared/api/playlistFullView.ts
  src/shared/api/playlistWithvideos.ts
  src/shared/api/uploadPlaylist.ts
  src/shared/api/users.ts
  src/shared/api/video.ts
  src/shared/api/youtube.ts
  src/shared/component/Dropbox.tsx
Labels: 🔨 Refactor

#63 Refactor : 프로필 이미지 수정
  src/pages/profile/Profile.tsx
  src/pages/profile/component/ProfileImageSection.tsx
  src/pages/profile/hooks/useUploadDeleteProfileImage.ts
  src/shared/Header.tsx
  src/shared/hooks/useProfileImage.ts
Labels: 🔨 Refactor

#65 Refactor : 플레이리스트 생성 시 유효성 검사 alert 적용
  src/pages/playlist/Create.tsx
Labels: 🔨 Refactor

#69 Refactor : svg 경로 대소문자 변경
  src/shared/Header.tsx
Labels: 🔨 Refactor

#72 Docs : README에 배포 링크 추가
  README.md
Labels: 🌏 Deploy, 📜 Docs
